name: OpenWrt IPK Package Builder with SDK and Matrix

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'GitHub Repository URL'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - sdk_ver: 21.02
            luci_ver: 19.07
            sdk_url: https://downloads.openwrt.org/releases/21.02.7/targets/x86/64/openwrt-sdk-21.02.7-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz

          - sdk_ver: 23.05
            luci_ver: 23.05
            sdk_url: https://downloads.openwrt.org/releases/23.05.5/targets/x86/64/openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz

    steps:
      - name: Extract Owner and Repo from URL
        id: extract_repo
        run: |
          REPO_URL="${{ github.event.inputs.repo_url }}"
          OWNER_REPO=$(echo $REPO_URL | sed -E 's#https://github.com/([^/]+)/([^/]+).*#\1/\2#')
          echo "Extracted owner/repo: $OWNER_REPO"
          echo "::set-output name=owner_repo::$OWNER_REPO"

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ steps.extract_repo.outputs.owner_repo }}
          path: source

      - name: Install packages
        run: |
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          echo "Install packages"
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils python3-setuptools rsync swig unzip zlib1g-dev file wget
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean

      - name: Cache openwrt SDK
        id: cache-sdk
        uses: actions/cache@v4
        with:
          path: sdk
          key: openwrt-luci-${{ matrix.luci_ver }}-x86_64

      - name: Initialization environment
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        run: |
          wget ${{ matrix.sdk_url }}
          file_name=$(echo ${{ matrix.sdk_url }} | awk -F/ '{print $NF}')
          mkdir sdk && tar -xJf $file_name -C ./sdk --strip-components=1
          cd sdk

      - name: Copy Package to SDK
        run: |
          cp -r source/* sdk/package/

      - name: Build IPK Package
        run: |
          cd sdk
          make defconfig
          make package/compile -j$(nproc)
          mkdir -p ../output/${{ matrix.sdk_ver }}
          find bin/packages -name '*.ipk' -exec cp {} ../output/${{ matrix.sdk_ver }} \;

      - name: Upload IPK Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: openwrt-ipk-packages-${{ matrix.sdk_ver }}
          path: output/${{ matrix.sdk_ver }}
